# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: ubuntu-20.04

variables:
  entryProject: 'eCommerce/eCommerce.csproj'
  buildConfiguration: 'Release'
  azureSubscription: 'fakeCommerce-connectionstring'
  appName: 'fakeecommerce'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1 SDK'
    inputs:
      version: '3.1.x'
      installationPath: '$(Agent.ToolsDirectory)/dotnet'

  - task: DotNetCoreCLI@2
    displayName: 'Restore the project'
    inputs:
      command: 'restore'
      projects: '$(entryProject)'
      feedsToUse: 'select'
      vstsFeed: 'FakeECommerceDevops/FakeECommerceFeed'
      includeNugetOrg: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: '$(entryProject)'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish the Project'
    inputs:
      command: 'publish'
      publishWebProjects: true
      zipAfterPublish: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactsStagingDirectory)'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: '$(azureSubscription)'
      appType: 'webAppLinux'
      WebAppName: '$(appName)'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'