# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: ubuntu-20.04

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'FakeECommerceDeployConnection'
  appName: 'fakeecommerce'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1 SDK'
    inputs:
      version: '3.1.x'
      installationPath: '$(Agent.ToolsDirectory)/dotnet'

  - task: DotNetCoreCLI@2
    displayName: 'Restore the project'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedToUse: 'select'
      vstsFeed: 'FakeEECommerceDevops/FakeEEComerceFeed'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish the Project'
    inputs:
      commands: 'publish'
      publishWebProjects: 'True'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactsStagingDirectory)'

  - task: AzureWebApp@1
    displayName: 'Azure Web App Deploy'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webAppLinux'
      appName: '$(appName)'
      package: '$(System.ArtifactsDirectory)/**/*.zip'
      resourceGroupName: 'FakeECommerceResource'