version: "3.8"
services:
  sqlserverdev:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      MSSQL_SA_PASSWORD:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    hostname: sql1
    container_name: sql1
    ports:
      - 1433:1433
    volumes:
      - sqldevvolume:/var/opt/mssql
volumes:
  sqldevvolume: