version: "3.8"
services:
  ePostgres:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_PASSWORD: eCommerce2020
      POSTGRES_DB: DevDatabase
    volumes:
      - $HOME/PostgresVolumes/eCommerce:/var/lib/postgresql/data
    container_name: postgresCommerce
    ports:
      - 5432:5432
  eRedis:
    image: "redis:6.0.9-alpine3.12"
    container_name: eCommerceRedis
    ports:
      - 6379:6379
    deploy:
      restart_policy:
        condition: on-failure
      