#!/bin/sh

# Shares the JWT authorization token to other testing endpoint scripts

token='eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkB0ZXN0LmNvbSIsImdpdmVuX25hbWUiOiJCb2IiLCJuYmYiOjE2MTE2OTI4MDgsImV4cCI6MTYxMTcwMDAwOCwiaWF0IjoxNjExNjkyODA4LCJpc3MiOiJsb2NhbGhvc3Q6NTAwMSJ9.FwhzybXsAGnRw5zo5A8vSXE_AY7pCq8RSxWpDsyspajr5Z4smJITOmUBQP4dAFrbRXTczOP4iWTeI9YpPYQXjQ'