#!/bin/sh

# Shares the JWT authorization token to other testing endpoint scripts

token='eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvYkB0ZXN0LmNvbSIsImdpdmVuX25hbWUiOiJCb2IiLCJuYmYiOjE2MDU4MTM1MDQsImV4cCI6MTYwNTgyMDcwNCwiaWF0IjoxNjA1ODEzNTA0LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.vH5v-jB968mHeCjb2ZL03UUBhTKnMenqGnR1OhVjJ9dDUF-D9b1b_OSMDTKl_cvGTjhEdGPTclROu7oPzKtLCA'